### ISSUE TITLE
Cachebusting

### ISSUE THREAD

**Issue by Addvilz** [rocky-linux/rockylinux.org-intro-spa#1]
It does not seem like assets are cache-busted for the initial SPA. We should make sure the deployments and changes result in caches being busted for browsers to avoid broken site.

**Comment by hbjydev** [comment]
I'm not sure in myself on how to go about solving this. At the moment it's just a Github Actions page deploy out of the `main` branch.

**Comment by hbjydev** [comment]
If someone could chip in and give me a hand that'd be good

**Comment by Addvilz** [comment]
@hbjydev maybe just edit `<link href="./style.css" rel="stylesheet" />` to include version, update per edit? Something like:

`<link href="./style.css?version=1" rel="stylesheet" />`

and bump that with every commit where CSS has changed.

**Comment by AxelSilverdew** [comment]
Yeah, I was just about to say

**Comment by AxelSilverdew** [comment]
You could also just have the query string autogenerated to be the unix timestamp

**Comment by Addvilz** [comment]
@AxelSilverdew no build tool yet, so :) manual!

**Comment by AxelSilverdew** [comment]
Okay, I'm opening a PR with your fix then

**Comment by AxelSilverdew** [comment]
Opened a PR here: https://github.com/rocky-linux/rockylinux.org-intro-spa/pull/2
